Catch a generic `Exception` when calling `Controller.run()`.
This should handle this exception which was seen:

```
Name: Vendor specific, Value: None
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jdoe/gitrepo/walkingpad-fitbit/walkingpadfitbit/main.py", line 52, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jdoe/gitrepo/walkingpad-fitbit/walkingpadfitbit/main.py", line 43, in main
    await monitor(
  File "/Users/jdoe/gitrepo/walkingpad-fitbit/walkingpadfitbit/interfaceadapters/walkingpad/monitor.py", line 100, in monitor
    await ctler.run(device)
  File "/Users/jdoe/gitrepo/walkingpad-fitbit/.venv/lib/python3.12/site-packages/ph4_walkingpad/pad.py", line 426, in run
    value = await client.read_gatt_descriptor(descriptor.handle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdoe/gitrepo/walkingpad-fitbit/.venv/lib/python3.12/site-packages/bleak/__init__.py", line 875, in read_gatt_descriptor
    return await self._backend.read_gatt_descriptor(handle, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdoe/gitrepo/walkingpad-fitbit/.venv/lib/python3.12/site-packages/bleak/backends/corebluetooth/client.py", line 303, in read_gatt_descriptor
    descriptor = self.services.get_descriptor(handle)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_descriptor'
```